//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecargasAdmin.SvcFAC_TKN {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenizeRequest", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class TokenizeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CardNumberField;
        
        private string CustomerReferenceField;
        
        private string ExpiryDateField;
        
        private string MerchantNumberField;
        
        private string SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerReference {
            get {
                return this.CustomerReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerReferenceField, value) != true)) {
                    this.CustomerReferenceField = value;
                    this.RaisePropertyChanged("CustomerReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MerchantNumber {
            get {
                return this.MerchantNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantNumberField, value) != true)) {
                    this.MerchantNumberField = value;
                    this.RaisePropertyChanged("MerchantNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenizeResponse", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class TokenizeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeTokenizeRequest", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class DeTokenizeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenPANField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantNumber {
            get {
                return this.MerchantNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantNumberField, value) != true)) {
                    this.MerchantNumberField = value;
                    this.RaisePropertyChanged("MerchantNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenPAN {
            get {
                return this.TokenPANField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenPANField, value) != true)) {
                    this.TokenPANField = value;
                    this.RaisePropertyChanged("TokenPAN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeTokenizeResponse", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class DeTokenizeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAN {
            get {
                return this.PANField;
            }
            set {
                if ((object.ReferenceEquals(this.PANField, value) != true)) {
                    this.PANField = value;
                    this.RaisePropertyChanged("PAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenListRequest", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class TokenListRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerReference {
            get {
                return this.CustomerReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerReferenceField, value) != true)) {
                    this.CustomerReferenceField = value;
                    this.RaisePropertyChanged("CustomerReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantNumber {
            get {
                return this.MerchantNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantNumberField, value) != true)) {
                    this.MerchantNumberField = value;
                    this.RaisePropertyChanged("MerchantNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenListResponse", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class TokenListResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RecargasAdmin.SvcFAC_TKN.TokenizedCard[] CardListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RecargasAdmin.SvcFAC_TKN.TokenizedCard[] CardList {
            get {
                return this.CardListField;
            }
            set {
                if ((object.ReferenceEquals(this.CardListField, value) != true)) {
                    this.CardListField = value;
                    this.RaisePropertyChanged("CardList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenizedCard", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class TokenizedCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenPANField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerReference {
            get {
                return this.CustomerReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerReferenceField, value) != true)) {
                    this.CustomerReferenceField = value;
                    this.RaisePropertyChanged("CustomerReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenPAN {
            get {
                return this.TokenPANField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenPANField, value) != true)) {
                    this.TokenPANField = value;
                    this.RaisePropertyChanged("TokenPAN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateTokenRequest", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class UpdateTokenRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CustomerReferenceField;
        
        private string ExpiryDateField;
        
        private string MerchantNumberField;
        
        private string SignatureField;
        
        private string TokenPANField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerReference {
            get {
                return this.CustomerReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerReferenceField, value) != true)) {
                    this.CustomerReferenceField = value;
                    this.RaisePropertyChanged("CustomerReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MerchantNumber {
            get {
                return this.MerchantNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantNumberField, value) != true)) {
                    this.MerchantNumberField = value;
                    this.RaisePropertyChanged("MerchantNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TokenPAN {
            get {
                return this.TokenPANField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenPANField, value) != true)) {
                    this.TokenPANField = value;
                    this.RaisePropertyChanged("TokenPAN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateTokenResponse", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class UpdateTokenResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenPANField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenPAN {
            get {
                return this.TokenPANField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenPANField, value) != true)) {
                    this.TokenPANField = value;
                    this.RaisePropertyChanged("TokenPAN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpiringCreditCardsRequest", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class ExpiringCreditCardsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndDateField;
        
        private string ExpiryDateField;
        
        private string MerchantIdField;
        
        private string SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EndDateField, value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MerchantId {
            get {
                return this.MerchantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantIdField, value) != true)) {
                    this.MerchantIdField = value;
                    this.RaisePropertyChanged("MerchantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateField, value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpiringCreditCardsResponse", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class ExpiringCreditCardsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RecargasAdmin.SvcFAC_TKN.ExpiringCreditCard[] ExpiringCreditCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RecargasAdmin.SvcFAC_TKN.ExpiringCreditCard[] ExpiringCreditCards {
            get {
                return this.ExpiringCreditCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiringCreditCardsField, value) != true)) {
                    this.ExpiringCreditCardsField = value;
                    this.RaisePropertyChanged("ExpiringCreditCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpiringCreditCard", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    [System.SerializableAttribute()]
    public partial class ExpiringCreditCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaskedPANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaskedPAN {
            get {
                return this.MaskedPANField;
            }
            set {
                if ((object.ReferenceEquals(this.MaskedPANField, value) != true)) {
                    this.MaskedPANField = value;
                    this.RaisePropertyChanged("MaskedPAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenCode {
            get {
                return this.TokenCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenCodeField, value) != true)) {
                    this.TokenCodeField = value;
                    this.RaisePropertyChanged("TokenCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.firstatlanticcommerce.com/gateway", ConfigurationName="SvcFAC_TKN.Tokenization")]
    public interface Tokenization {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/Tokenize", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/TokenizeResponse")]
        RecargasAdmin.SvcFAC_TKN.TokenizeResponse Tokenize(RecargasAdmin.SvcFAC_TKN.TokenizeRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/Tokenize", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/TokenizeResponse")]
        System.Threading.Tasks.Task<RecargasAdmin.SvcFAC_TKN.TokenizeResponse> TokenizeAsync(RecargasAdmin.SvcFAC_TKN.TokenizeRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/DeTokenize", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/DeTokenizeResponse")]
        RecargasAdmin.SvcFAC_TKN.DeTokenizeResponse DeTokenize(RecargasAdmin.SvcFAC_TKN.DeTokenizeRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/DeTokenize", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/DeTokenizeResponse")]
        System.Threading.Tasks.Task<RecargasAdmin.SvcFAC_TKN.DeTokenizeResponse> DeTokenizeAsync(RecargasAdmin.SvcFAC_TKN.DeTokenizeRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/TokenList", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/TokenListResponse")]
        RecargasAdmin.SvcFAC_TKN.TokenListResponse TokenList(RecargasAdmin.SvcFAC_TKN.TokenListRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/TokenList", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/TokenListResponse")]
        System.Threading.Tasks.Task<RecargasAdmin.SvcFAC_TKN.TokenListResponse> TokenListAsync(RecargasAdmin.SvcFAC_TKN.TokenListRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/UpdateToken", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/UpdateTokenResponse" +
            "")]
        RecargasAdmin.SvcFAC_TKN.UpdateTokenResponse UpdateToken(RecargasAdmin.SvcFAC_TKN.UpdateTokenRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/UpdateToken", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/UpdateTokenResponse" +
            "")]
        System.Threading.Tasks.Task<RecargasAdmin.SvcFAC_TKN.UpdateTokenResponse> UpdateTokenAsync(RecargasAdmin.SvcFAC_TKN.UpdateTokenRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/ExpiringCreditCards" +
            "", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/ExpiringCreditCards" +
            "Response")]
        RecargasAdmin.SvcFAC_TKN.ExpiringCreditCardsResponse ExpiringCreditCards(RecargasAdmin.SvcFAC_TKN.ExpiringCreditCardsRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/ExpiringCreditCards" +
            "", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/Tokenization/ExpiringCreditCards" +
            "Response")]
        System.Threading.Tasks.Task<RecargasAdmin.SvcFAC_TKN.ExpiringCreditCardsResponse> ExpiringCreditCardsAsync(RecargasAdmin.SvcFAC_TKN.ExpiringCreditCardsRequest Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TokenizationChannel : RecargasAdmin.SvcFAC_TKN.Tokenization, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenizationClient : System.ServiceModel.ClientBase<RecargasAdmin.SvcFAC_TKN.Tokenization>, RecargasAdmin.SvcFAC_TKN.Tokenization {
        
        public TokenizationClient() {
        }
        
        public TokenizationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenizationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenizationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenizationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RecargasAdmin.SvcFAC_TKN.TokenizeResponse Tokenize(RecargasAdmin.SvcFAC_TKN.TokenizeRequest Request) {
            return base.Channel.Tokenize(Request);
        }
        
        public System.Threading.Tasks.Task<RecargasAdmin.SvcFAC_TKN.TokenizeResponse> TokenizeAsync(RecargasAdmin.SvcFAC_TKN.TokenizeRequest Request) {
            return base.Channel.TokenizeAsync(Request);
        }
        
        public RecargasAdmin.SvcFAC_TKN.DeTokenizeResponse DeTokenize(RecargasAdmin.SvcFAC_TKN.DeTokenizeRequest Request) {
            return base.Channel.DeTokenize(Request);
        }
        
        public System.Threading.Tasks.Task<RecargasAdmin.SvcFAC_TKN.DeTokenizeResponse> DeTokenizeAsync(RecargasAdmin.SvcFAC_TKN.DeTokenizeRequest Request) {
            return base.Channel.DeTokenizeAsync(Request);
        }
        
        public RecargasAdmin.SvcFAC_TKN.TokenListResponse TokenList(RecargasAdmin.SvcFAC_TKN.TokenListRequest Request) {
            return base.Channel.TokenList(Request);
        }
        
        public System.Threading.Tasks.Task<RecargasAdmin.SvcFAC_TKN.TokenListResponse> TokenListAsync(RecargasAdmin.SvcFAC_TKN.TokenListRequest Request) {
            return base.Channel.TokenListAsync(Request);
        }
        
        public RecargasAdmin.SvcFAC_TKN.UpdateTokenResponse UpdateToken(RecargasAdmin.SvcFAC_TKN.UpdateTokenRequest Request) {
            return base.Channel.UpdateToken(Request);
        }
        
        public System.Threading.Tasks.Task<RecargasAdmin.SvcFAC_TKN.UpdateTokenResponse> UpdateTokenAsync(RecargasAdmin.SvcFAC_TKN.UpdateTokenRequest Request) {
            return base.Channel.UpdateTokenAsync(Request);
        }
        
        public RecargasAdmin.SvcFAC_TKN.ExpiringCreditCardsResponse ExpiringCreditCards(RecargasAdmin.SvcFAC_TKN.ExpiringCreditCardsRequest Request) {
            return base.Channel.ExpiringCreditCards(Request);
        }
        
        public System.Threading.Tasks.Task<RecargasAdmin.SvcFAC_TKN.ExpiringCreditCardsResponse> ExpiringCreditCardsAsync(RecargasAdmin.SvcFAC_TKN.ExpiringCreditCardsRequest Request) {
            return base.Channel.ExpiringCreditCardsAsync(Request);
        }
    }
}
